### ISSUE TITLE
need to fix prometheus yml config

### ISSUE THREAD

**Issue by juzza88** [unpoller/unpoller#352]
It wont work following your guide. 

The poller doesnt know about the /metrics. So you need to add the metrics path into the prometheus.yml.

 Like below:
```yaml
- job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
    - targets: ['localhost:9130']
    metrics_path: /metrics
```
