### ISSUE TITLE
Stumped on grafna db initialization (docker)

### ISSUE THREAD

**Issue by scyto** [unpoller/unpoller#386]
Hi,  decided to use this project to help me learn portainer templates and stacks.

I have a docker host / portainer.
I have an NFS share where I store state data (mapped as volume into container, not as a bind mount).
Influx creates its dirs just fine, poller is sending the data to influx just fine.

Grafana creates the plugins dir and downloads the plugs in on first boot ok.
It creates a grafana.db file - but that stays at 0 bytes and never starts listening on its port.

the log looks likes this:
```
✔ Downloaded grafana-clock-panel v1.2.0 zip successfully
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
✔ Downloaded natel-discrete-panel v0.1.1 zip successfully
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
✔ Downloaded grafana-piechart-panel v1.6.2 zip successfully
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
t=2021-12-23T02:18:54+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations" logger=settings
t=2021-12-23T02:18:54+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." logger=settings
t=2021-12-23T02:18:54+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2021-12-23T02:18:54+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
t=2021-12-23T02:18:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=admin"
t=2021-12-23T02:18:54+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2021-12-23T02:18:54+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2021-12-23T02:18:54+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2021-12-23T02:18:54+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2021-12-23T02:18:54+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2021-12-23T02:18:54+0000 lvl=info msg="App mode production" logger=settings
t=2021-12-23T02:18:54+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-12-23T02:18:54+0000 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/var/lib/grafana/grafana.db mode=-rwxrwxrwx expected=-rw-r-----
t=2021-12-23T02:25:15+0000 lvl=eror msg="failed to determine the status of alerting engine. Enable either legacy or unified alerting explicitly and try again" logger=migrator err="failed to verify if the 'alert' table exists: database is locked"
```

So i am stumped, it had the rights to create folders, download files etc
but gets stuck here - any ideas, it shouldnt mater it has more rights should it?

**Comment by davidnewhall** [comment]
Can you connect to it on port 3000?

**Comment by scyto** [comment]
no it never seems to start listening on that as far as i can tell

**Comment by davidnewhall** [comment]
So we're troubleshooting a Grafana container. Can you share the configuration and Docker image, etc?

**Comment by scyto** [comment]
here is the stack
```
version: "3"
services:
  up_influxdb:
#    container_name: up_influxdb
#    restart: unless-stopped
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - syn01_portainer_nfs:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=unifi
      - INFLUXDB_ADMIN_USER=unifi
      - INFLUXDB_ADMIN_PASSWORD=unifi
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  up_grafana:
#    container_name: up_grafana
    image: grafana/grafana
#    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - syn01_portainer_nfs:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  un-poller:
#    container_name: up-poller
#    restart: unless-stopped
    image: golift/unifi-poller:latest
    depends_on:
      - influxdb
      - grafana
    environment:
      - UP_UNIFI_DEFAULT_URL=https://192.168.1.1
      - UP_UNIFI_DEFAULT_USER=unifi-poller
      - UP_UNIFI_DEFAULT_PASS=redacted
      - UP_UNIFI_DEFAULT_SAVE_SITES=true
      - UP_UNIFI_DEFAULT_SITE_0=default
      - UP_INFLUXDB_URL=http://{{.Node.Hostname}}.mydomain.com:8086
    volumes:
      - syn01_portainer_nfs:/config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


volumes:
  syn01_portainer_nfs:
    external: true
```
