### ISSUE TITLE
Latest version not starting

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [unpoller/unpoller#443]
Docker logs unifipoller:

`2022/11/23 15:26:15 [ERROR] finding file: stat /etc/unifi-poller/up.conf: no such file or directory`

docker-compose.yml :

```
version: '3.8'
services:

  unifipoller:
    container_name: unifi-poller
    restart: always
    image: ghcr.io/unpoller/unpoller:latest
    environment:
      - UP_INFLUXDB_DB=unifipoller
      - UP_INFLUXDB_USER=USER
      - UP_INFLUXDB_PASS=PASS
      - UP_INFLUXDB_URL=http://DB
      - UP_UNIFI_DEFAULT_USER=USER
      - UP_UNIFI_DEFAULT_PASS=PW
      - UP_UNIFI_DEFAULT_URL=https://IP
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DEFAULT_SAVE_DPI=true

```
