### ISSUE TITLE
Docker compose with .env file not working on Ubuntu

### ISSUE THREAD

**Issue by thetravellor** [unpoller/unpoller#536]
Hello, I am following the docker compose example using a .env file

influxdb2 is crashing continuously, with the following output:

```
bolt-path: /var/lib/influxdb2/influxd.bolt
engine-path: /var/lib/influxdb2/engine
nats-port: 4222
http-bind-address: :9999
2023-03-29T01:42:08.170680949Z  info    booting influxd server in the background        {"system": "docker"}
ts=2023-03-29T01:42:08.283123Z lvl=info msg="Welcome to InfluxDB" log_id=0grlJnbW000 version=v2.5.1 commit=5b6fdbf05d build_date=2022-11-02T18:06:28Z log_level=info
ts=2023-03-29T01:42:08.283157Z lvl=warn msg="nats-port argument is deprecated and unused" log_id=0grlJnbW000
ts=2023-03-29T01:42:08.290908Z lvl=info msg="Resources opened" log_id=0grlJnbW000 service=bolt path=/var/lib/influxdb2/influxd.bolt
ts=2023-03-29T01:42:08.291079Z lvl=info msg="Resources opened" log_id=0grlJnbW000 service=sqlite path=/var/lib/influxdb2/influxd.sqlite
ts=2023-03-29T01:42:08.292568Z lvl=info msg="Bringing up metadata migrations" log_id=0grlJnbW000 service="KV migrations" migration_count=20
ts=2023-03-29T01:42:08.428299Z lvl=info msg="Using data dir" log_id=0grlJnbW000 service=storage-engine service=store path=/var/lib/influxdb2/engine/data
ts=2023-03-29T01:42:08.428448Z lvl=info msg="Compaction settings" log_id=0grlJnbW000 service=storage-engine service=store max_concurrent_compactions=2 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648
ts=2023-03-29T01:42:08.428466Z lvl=info msg="Open store (start)" log_id=0grlJnbW000 service=storage-engine service=store op_name=tsdb_open op_event=start
ts=2023-03-29T01:42:08.428549Z lvl=info msg="Open store (end)" log_id=0grlJnbW000 service=storage-engine service=store op_name=tsdb_open op_event=end op_elapsed=0.078ms
ts=2023-03-29T01:42:08.428584Z lvl=info msg="Starting retention policy enforcement service" log_id=0grlJnbW000 service=retention check_interval=30m
ts=2023-03-29T01:42:08.428599Z lvl=info msg="Starting precreation service" log_id=0grlJnbW000 service=shard-precreation check_interval=10m advance_period=30m
ts=2023-03-29T01:42:08.430224Z lvl=info msg="Starting query controller" log_id=0grlJnbW000 service=storage-reads concurrency_quota=1024 initial_memory_bytes_quota_per_query=9223372036854775807 memory_bytes_quota_per_query=9223372036854775807 max_memory_bytes=0 queue_size=1024
ts=2023-03-29T01:42:08.435915Z lvl=info msg="Configuring InfluxQL statement executor (zeros indicate unlimited)." log_id=0grlJnbW000 max_select_point=0 max_select_series=0 max_select_buckets=0
ts=2023-03-29T01:42:08.445299Z lvl=info msg=Starting log_id=0grlJnbW000 service=telemetry interval=8h
ts=2023-03-29T01:42:08.445459Z lvl=info msg=Listening log_id=0grlJnbW000 service=tcp-listener transport=http addr=:9999 port=9999
2023-03-29T01:42:09.178473841Z  info    pinging influxd...      {"system": "docker", "ping_attempt": "0"}
2023-03-29T01:42:09.186387469Z  info    got response from influxd, proceeding   {"system": "docker", "total_pings": "1"}
Error: password is too short
2023-03-29T01:42:09.195115110Z  warn    cleaning bolt and engine files to prevent conflicts on retry   
 {"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt", "engine_path": "/var/lib/influxdb2/engine"}
```

This is docker compose:

```
# This is for unifi-poller v2.
version: '3'
services:
  influxdb:
    restart: always
    image: influxdb:2.5
    ports:
      - '8086:8086'
      - '9999:9999'
    volumes:
      - influxdb-storage:/var/lib/influxdb
#      - influxdb-storage:/data/influxdb2
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
  chronograf:
    image: chronograf:latest
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
#      - chronograf-storage:/data/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
#      - grafana-storage:/data/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
  unifi-poller:
    restart: always
    image: ghcr.io/unpoller/unpoller:${POLLER_TAG}
    depends_on:
      - grafana
      - influxdb
      - chronograf
    environment:
      - UP_INFLUXDB_DB=${INFLUXDB_DB}
      - UP_INFLUXDB_USER=${INFLUXDB_ADMIN_USER}
      - UP_INFLUXDB_PASS=${INFLUXDB_ADMIN_PASSWORD}
      - UP_INFLUXDB_ORG=${INFLUXDB_ORG}
      - UP_INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - UP_INFLUXDB_AUTH_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - UP_INFLUXDB_URL=http://influxdb:8086
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=${POLLER_DEBUG}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${POLLER_SAVE_DPI}
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:

```

```
stephen@frigate:/data/unpoller$ docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS                                  PORTS                                                                                                                                                                                            NAMES
d6f0f85d286e   ghcr.io/unpoller/unpoller:latest                       "/usr/bin/unpoller"      19 seconds ago   Up 17 seconds                                                                                                                                                                                                                            unpoller-unifi-poller-1
3719a677f283   grafana/grafana:latest                                 "/run.sh"                19 seconds ago   Up 17 seconds                           0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                                                                                        unpoller-grafana-1
d7521425c25f   chronograf:latest                                      "/entrypoint.sh chro…"   19 seconds ago   Up 17 seconds                           0.0.0.0:8888->8888/tcp, :::8888->8888/tcp                                                                                                                                                        unpoller-chronograf-1
8d48d1b6ca0d   influxdb:2.5                                           "/entrypoint.sh infl…"   19 seconds ago   Restarting (1) Less than a second ago                                                                                                                                                                                                    unpoller-influxdb-1
1a5eb6ce653c   ghcr.io/blakeblackshear/frigate:dev-1bf3b83-tensorrt   "/init"                  5 days ago       Up 4 days                               0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:5000->5000/tcp, :::5000->5000/tcp, 0.0.0.0:8554-8555->8554-8555/tcp, :::8554-8555->8554-8555/tcp, 0.0.0.0:8555->8555/udp, :::8555->8555/udp   frigate
stephen@frigate:/data/unpoller$ 
```

In addition influxdb2 crashing is it possible to map the 3 storage locations to another filesystem, as docker defaults to the / filesystem on my ubuntu installation, and I would like unpoller to have all its data files on /data (/ is too small)
