### ISSUE TITLE
Influx2 unauthorized with token

### ISSUE THREAD

**Issue by AlfaJackal** [unpoller/unpoller#557]
Hi!

I created a new bucket and an api token for influx2db from the scratch. Unfortunately I am not able to get access from unpoller to my bucket:

```
unpoller    | 2023/05/16 09:34:35 [ERROR] influxdb.Write(points): {"code":"unauthorized","message":"Unauthorized"}
```

```
unpoller    | 2023/05/16 09:34:02 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
unpoller    | 2023/05/16 09:34:02 [INFO] UniFi Poller v2.1.3 Starting Up! PID: 1
unpoller    | 2023/05/16 09:34:03 [INFO] Found 1 site(s) on controller https://10.0.0.2: default (BlackMesa)
unpoller    | 2023/05/16 09:34:03 [INFO] Configured UniFi Controller 1 of 1:
unpoller    | 2023/05/16 09:34:03 [INFO]    => URL: https://10.0.0.2 (verify SSL: false)
unpoller    | 2023/05/16 09:34:03 [INFO]    => Version:  (9608a9fc-6a75-55ba-b779-ae8f896eb60d)
unpoller    | 2023/05/16 09:34:03 [INFO]    => Username: influx (has password: true)
unpoller    | 2023/05/16 09:34:03 [INFO]    => Hash PII / Poll Sites: false / all
unpoller    | 2023/05/16 09:34:03 [INFO]    => Save Sites / Save DPI: true / true (metrics)
unpoller    | 2023/05/16 09:34:03 [INFO]    => Save Events / Save IDS: true / true (logs)
unpoller    | 2023/05/16 09:34:03 [INFO]    => Save Alarms / Anomalies: true / true (logs)
unpoller    | 2023/05/16 09:34:03 [INFO]    => Save Rogue APs: true
unpoller    | 2023/05/16 09:34:03 [INFO] Prometheus config missing (or disabled), Prometheus HTTP listener disabled!
unpoller    | 2023/05/16 09:34:03 [INFO] Internal web server disabled!
unpoller    | 2023/05/16 09:34:03 [INFO] Loki config missing (or disabled), Loki output disabled!
unpoller    | 2023/05/16 09:34:03 [INFO] Poller->InfluxDB started, interval: 30s, dp: true, db: unifi, url: http://10.10.0.111:8086
unpoller    | 2023/05/16 09:34:35 [ERROR] influxdb.Write(points): {"code":"unauthorized","message":"Unauthorized"}
```

This is my .yml. Editing `unpoller.conf`directly does not make a difference:
```
version: "3"
services:
  unpoller:
    container_name: unpoller
    restart: unless-stopped
    image: golift/unifi-poller:latest
    volumes:
      - ./config/unpoller.conf:/etc/unifi-poller/up.conf
    environment:
      - UP_INFLUXDB_ORG=LambdaCore
      - UP_INFLUXDB_BUCKET=unifi
      - UP_INFLUXDB_USEV2=true
      - UP_INFLUXDB_AUTH_TOKEN="vEryL0ngT0k3n"
      - UP_INFLUXDB_URL=http://10.10.0.111:8086
```

What am I missing here?

Deleting env variables from docker-compose and adding credentials directly to unpoller.conf also does not help.

unpoller.conf:
```
[influxdb]
  disable = false
  url  = "http://10.10.0.111:8086"
  org = "LambdaCore"
  bucket = "unifi"
  auth_token = "vEryL0ngT0k3n"
  verify_ssl = false
  interval = "30s"
  dead_ports = true
```
