### ISSUE TITLE
Grafana Prometheus dashboards "No data to show"

### ISSUE THREAD

**Issue by d-mcknight** [unpoller/unpoller#562]
New to Grafana and Prometheus, but I followed [the unpoller docs](https://unpoller.com/docs/install/grafana#dashboard-installation-instructions) to try and set this up in unRaid. I tried loading this [dashboard](https://grafana.com/grafana/dashboards/11315-unifi-poller-client-insights-prometheus/) and some others, but none of them render any data.

The UniFi-Poller container appears to be working (logs below) and Prometheus shows the endpoint as being up (config also below). From Grafana, I can query and get a response for `unifipoller_build_info`  using the Prometheus data source and the same Prometheus data source is providing unRaid stats that are working as expected.

last couple unPoller logs
```
2023/06/10 22:20:19 [INFO] UniFi Measurements Exported. Site: 1, Client: 38, UAP: 2, USG/UDM: 0, USW: 2, DPI Site/Client: 0/0, Desc: 172, Metric: 1849, Err: 0, 0s: 648, Req/Total: 68.4ms / 73.7ms
2023/06/10 22:20:49 [INFO] UniFi Measurements Exported. Site: 1, Client: 38, UAP: 2, USG/UDM: 0, USW: 2, DPI Site/Client: 0/0, Desc: 172, Metric: 1849, Err: 0, 0s: 646, Req/Total: 71.9ms / 77ms
```
prometheus config snippet
```yaml
  - job_name: unraid_unifi
    scrape_interval: 30s
    static_configs:
      - targets: ['https://unifi.domain.tld']  # Unifi container
    metrics_path: /scrape
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: '192.168.1.100:9031'
```
