### ISSUE TITLE
influxdb2client E! Write error: Unexpected status code 401

### ISSUE THREAD

**Issue by SemoTech** [unpoller/unpoller#623]
Hey everyone, just set this up and there seem to be permission issues writing to the influxdb that I cannot seem to track down and fix.

For reference, I deployed a new unpoller 2.9.2 via latest versions of docker and Portainer on a fresh Ubuntu Server 22.04 to connect to my UDM-SE.
 
Here is the docker version info:

```
root@upoller:~# docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
In Portainer I then used the stack name "unifi-poller" and the following configuration:

```
# This is for unifi-poller v2.
version: '3'
services:
  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - /docker/unifi-poller/influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=unpoller
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=unpoller
      - INFLUXDB_ADMIN_PASSWORD=unpoller-password
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=unpoller
      - DOCKER_INFLUXDB_INIT_PASSWORD=unpoller-password
      - DOCKER_INFLUXDB_INIT_ORG=unpoller
      - DOCKER_INFLUXDB_INIT_BUCKET=unpoller
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=unpoller-token
    labels:
      - com.centurylinklabs.watchtower.enable=true      
  chronograf:
    image: chronograf:latest
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - /docker/unifi-poller/chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=unpoller
      - INFLUXDB_PASSWORD=unpoller-password
    labels:
      - com.centurylinklabs.watchtower.enable=true
  grafana:
    image: grafana/grafana:latest
    restart: always
    user: "0" 
    ports:
      - '3000:3000'
    volumes:
      - /docker/unifi-poller/grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=gadmin
      - GF_SECURITY_ADMIN_PASSWORD=gadmin-password
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    labels:
      - com.centurylinklabs.watchtower.enable=true      
  unpoller:
    restart: always
    image: ghcr.io/unpoller/unpoller:latest
    depends_on:
      - grafana
      - influxdb
      - chronograf
    environment:
      - UP_INFLUXDB_DB=unpoller
      - UP_INFLUXDB_USER=unpoller
      - UP_INFLUXDB_PASS=unpoller-password
      - UP_INFLUXDB_ORG=unpoller
      - UP_INFLUXDB_BUCKET=unpoller
      - UP_INFLUXDB_AUTH_TOKEN=unpoller-token
      - UP_INFLUXDB_URL=http://influxdb:8086
      - UP_UNIFI_DEFAULT_USER=UniFi-Poller
      - UP_UNIFI_DEFAULT_PASS=UniFi-Password
      - UP_UNIFI_DEFAULT_URL=https://192.168.50.2
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DEFAULT_SAVE_DPI=false
    volumes:
      - /docker/unifi-poller/unpoller/up.conf:/etc/unpoller/up.conf
    labels:
      - com.centurylinklabs.watchtower.enable=true
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
```
The result were 4 containers:
unifi-poller-chronograf
unifi-poller-grafana
unifi-poller-influxdb
unifi-poller-unpoller

Here is the [influxdb] section from "up.conf" file for unpoller, located in /docker/unifi-poller/unpoller 

```
[influxdb]
  disable = false
  # InfluxDB does not require auth by default, so the user/password are probably unimportant.
  url  = "http://127.0.0.1:8086"
  user = "unpoller"
  # Password for InfluxDB user (above).
  # If the password provided here begins with file:// then the password is read in from
  # the file path that follows the file:// prefix. ex: file:///etc/influxdb/passwd.file
  pass = "unpoller-password"
  # Be sure to create this database. See the InfluxDB Wiki page for more info.
  db = "unpoller"
  # If your InfluxDB uses a valid SSL cert, set this to true.
  verify_ssl = false
  # The UniFi Controller only updates traffic stats about every 30 seconds.
  # Setting this to something lower may lead to "zeros" in your data.
  # If you're getting zeros now, set this to "1m"
  interval = "30s"
  ## Record data for disabled or down (unlinked) switch ports.
  dead_ports = false

```

At 1st I had a permissions issue with grafana but after adding [ user: "0" ] to the stack for it, that was solved.
Chronograf is not showing any errors, however both "unifi-poller-influxdb" and "unifi-poller-unpoller" are!

"unifi-poller-unpoller" started up OK but then there are errors about Writing, as follows:

```
2023/10/05 15:57:34 [INFO] Loading Configuration File: /etc/unpoller/up.conf
2023/10/05 15:57:34 [INFO] UniFi Poller v2.9.2 Starting Up! PID: 1
2023/10/05 15:57:35 [INFO] Found 1 site(s) on controller https://192.168.0.2: default (Default)
2023/10/05 15:57:35 [INFO] Configured UniFi Controller 1 of 1:
2023/10/05 15:57:35 [INFO]    => URL: https://192.168.50.2 (verify SSL: false)
2023/10/05 15:57:35 [INFO]    => Version:  (64f68fb6-987c-5046-a2e7-594ad776cc51)
2023/10/05 15:57:35 [INFO]    => Username: UniFi-Poller (has password: true)
2023/10/05 15:57:35 [INFO]    => Hash PII false / Drop PII false / Poll Sites: all
2023/10/05 15:57:35 [INFO]    => Save Sites true / Save DPI false (metrics)
2023/10/05 15:57:35 [INFO]    => Save Events false / Save IDS true (logs)
2023/10/05 15:57:35 [INFO]    => Save Alarms false / Anomalies false (logs)
2023/10/05 15:57:35 [INFO]    => Save Rogue APs: false
2023/10/05 15:57:35 [INFO] Prometheus is enabled
2023/10/05 15:57:35 [INFO] InfluxDB enabled
2023/10/05 15:57:35 [INFO] Poller->InfluxDB started, version: 2, interval: 30s, dp: false, db: unpoller, url: http://influxdb:8086, bucket: unpoller, org: unpoller
2023/10/05 15:57:35 [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unpoller
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
2023/10/05 15:58:06 influxdb2client E! Write error: Unexpected status code 401
```
Back at the ""unifi-poller-influxdb" I see this all over it's logs:

```
[httpd] 172.19.0.5 - - [05/Oct/2023:16:11:36 +0000] "POST /api/v2/write?bucket=unpoller&org=unpoller&precision=ns HTTP/1.1 " 401 55 "-" "influxdb-client-go/2.12.3 (linux; amd64)" dbf40a0b-6399-11ee-8135-0242ac130002 15
[httpd] 172.19.0.5 - - [05/Oct/2023:16:12:07 +0000] "POST /api/v2/write?bucket=unpoller&org=unpoller&precision=ns HTTP/1.1 " 401 55 "-" "influxdb-client-go/2.12.3 (linux; amd64)" ee125759-6399-11ee-8136-0242ac130002 45
[httpd] 172.19.0.5 - - [05/Oct/2023:16:12:07 +0000] "POST /api/v2/write?bucket=unpoller&org=unpoller&precision=ns HTTP/1.1 " 401 55 "-" "influxdb-client-go/2.12.3 (linux; amd64)" ee126ffa-6399-11ee-8137-0242ac130002 21
[httpd] 172.19.0.5 - - [05/Oct/2023:16:12:07 +0000] "POST /api/v2/write?bucket=unpoller&org=unpoller&precision=ns HTTP/1.1 " 401 55 "-" "influxdb-client-go/2.12.3 (linux; amd64)" ee1288c3-6399-11ee-8138-0242ac130002 18
...
```
I have triple checked that the passwords match in the stack file and also connected to the influxdb container via the shell and logged directly into the influx database with the password used in the stack file, and issued the "SHOW DATABASES" command to ensure the credentials are correct and the "unpoller" user was indeed an admin:

```
root@8b93167bafcc:/# influx -username unpoller -password unpollel-password
Connected to http://localhost:8086 version 1.8.10
InfluxDB shell version: 1.8.10
> SHOW DATABASES
name: databases
name
----
unpoller
_internal
> SHOW USERS
user     admin
----     -----
unpoller true
> SHOW RETENTION POLICIES ON "unpoller"
name             duration  shardGroupDuration replicaN default
----             --------  ------------------ -------- -------
autogen          0s        168h0m0s           1        true
retention_policy 8760h0m0s 168h0m0s           1        false
```
**Any ideas how to fix this and get unpoller working properly?**
