### ISSUE TITLE
Docker Compose Instructions & example files don't work

### ISSUE THREAD

**Issue by h4rryb** [unpoller/unpoller#766]
Hello,

I've tried following your insttructions from the website, and from https://github.com/unpoller/unpoller/tree/master/init/docker, but utilising the provided files, and just adding in my UniFi controller credentials doesn't work. It's able to connect to the UniFi device, and Grafana is able to start, but the terminal continuously gets the following error message, and I'm not able to connect the InfluxDB to Grafana - any ideas?

influxdb2client E! Write error: 404 Not Found: database not found: "unpoller"

**Comment by rossdargan** [comment]
Yeah, the documentation is pretty poor. That is a guide for using influxdb 2 (which the documentation is saying don't use).
I had to switch to this:
```
  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - /docker/unifipoller/influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}   
```

I then had to follow the instructions to manually create the user and db. I also couldn't get the token working so I set http_auth_enabled to false.

After that I did get it all working. good luck!
